dist: trusty
sudo: true

language: cpp
before_install:
  -sudo apt install g++
  -sudo apt install libboost-dev # For Boost
  -sudo apt install libssl-dev # For OpenSSL
script:
  - cmake -H. -Bbuild
  - cmake --build build

notifications:
  email: false