dist: trusty
sudo: false

language: cpp
before_install:
  -apt install libboost-dev # For Boost
  -apt install libssl-dev # For OpenSSL
script:
  - cmake -H. -Bbuild
  - cmake --build build

notifications:
  email: false
